### ISSUE TITLE
headphone jack / CX20724

### ISSUE THREAD

**Issue by ananich** [insanelydeepak/cloverHDA-for-Mac-OS-10.11-El-Capitan#1]
Tested Laptop/Conexant%20CX20724. Everything works except headphone jack.

**Comment by insanelydeepak** [comment]
can you provide codec_dump ?

**Comment by ananich** [comment]
Please find two files attached
[codec0.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-10.11-El-Capitan/files/524179/codec0.txt)
[codec2.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-10.11-El-Capitan/files/524178/codec2.txt)

**Comment by insanelydeepak** [comment]
try this 

[Conexant CX20724_v2.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-10.11-El-Capitan/files/526210/Conexant.CX20724_v2.zip)

**Comment by ananich** [comment]
Tested. CX20724_v2 does not work at all. There is a silence instead of sound. And also system crashed in HDMI attach.

**Comment by insanelydeepak** [comment]
try this one 
let me know which detects your Headphone 

[20724.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-10.11-El-Capitan/files/535990/20724.zip)

**Comment by ananich** [comment]
This one crashes when HDMI is attached: 20724.zip

However I realized that I have not tested carefully enough. I wan to give a try to Conexant CX20724_v2.zip next week once again.

**Comment by ananich** [comment]
Can not follow instructions in README because there is no DTGP definition in my DSDT. DSDT compilation fails.

**Comment by insanelydeepak** [comment]
Hi , sorry I was kinda busy 
just apply rehabman HDEF Patch , enough

**Comment by insanelydeepak** [comment]
Hi 
I'm closing issue now , if it still then
feel free to re-open 

Thanks
