### ISSUE TITLE
The ALC271x does not work

### ISSUE THREAD

**Issue by 610110707** [insanelydeepak/cloverHDA-for-Mac-OS-10.11-El-Capitan#2]
Acer 5820tg
HM55
Sierra 10.12.1 Beta
[codec.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-10.11-El-Capitan/files/540056/codec.txt)

**Comment by insanelydeepak** [comment]
hello 
this repo is not for 10.12 
you should try this 
https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/blob/master/Laptop/ALC271x.zip
or this 
https://github.com/insanelydeepak/Patched-AppleHDA-for-Mac-OS-Sierra-10.12/blob/master/Laptop's/AppleHDA-276.26-ALC271x.zip
