### ISSUE TITLE
no audio device ALC255 (ALC3234)

### ISSUE THREAD

**Issue by gustavocmotta** [insanelydeepak/cloverHDA-for-Mac-OS-10.11-El-Capitan#4]
No input device found.
Don't know how to extract clover boot log.

[codec_dump.txt.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-10.11-El-Capitan/files/737057/codec_dump.txt.zip)
[kextstat.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-10.11-El-Capitan/files/737053/kextstat.txt)
[ioregistry.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-10.11-El-Capitan/files/737054/ioregistry.zip)
[config.plist.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-10.11-El-Capitan/files/737055/config.plist.zip)

![screen shot](https://cloud.githubusercontent.com/assets/3124554/22398667/84bda258-e563-11e6-8e6b-7ea1ab1b691a.png)
![screen shot2](https://cloud.githubusercontent.com/assets/3124554/22398679/c36651e4-e563-11e6-8ba5-b6e14d067d58.png)

**Comment by insanelydeepak** [comment]
Hi , sorry I was kinda busy 
did you rebuild caches ?? it doesn't show cloverHDA loaded

**Comment by insanelydeepak** [comment]
Hi 
I'm closing issue now , if it still then
feel free to re-open 

Thanks
