### ISSUE TITLE
ALC256_v2 - Working Combojack No Sound

### ISSUE THREAD

**Issue by z04n** [insanelydeepak/cloverHDA-for-Mac-OS-10.11-El-Capitan#6]
Hi Deepak,

Inspiron 5000 5567 with ALC3246 on 10.11.6.  System info and sound in sys preferences shows that it's working, but no audio from speakers or headphones.  Attached troubleshooting files per your requirements.  For Csr, I'm using 0x67 as my laptop will not boot with 0x3.  Using EasyKext, I've performed the cache/permission step after install.
[config.plist.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-10.11-El-Capitan/files/756649/config.plist.zip)
[DumpLog.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-10.11-El-Capitan/files/756650/DumpLog.txt)
[IOReg.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-10.11-El-Capitan/files/756651/IOReg.zip)
[kextstat.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-10.11-El-Capitan/files/756652/kextstat.zip)
![screen shot](https://cloud.githubusercontent.com/assets/25474105/22678832/0efc5220-eccb-11e6-810f-88fb0d8c4fd4.png)

**Comment by z04n** [comment]
I was able to update to 10.12 and it started working.  Headphones give static, but assuming that can be fixed with CodecCommander.

**Comment by insanelydeepak** [comment]
Hi 
sorry I'm too much busy so don't have a time for hack stuff , will get you when available
