### ISSUE TITLE
IDT92HD91BXX works output but no input

### ISSUE THREAD

**Issue by ahmed-shehata** [insanelydeepak/cloverHDA-for-Mac-OS-10.11-El-Capitan#7]
Hi,

I have installed the cloverHDA kext for IDT92HD91BXX, I am getting audio, but no input (microphone), I am using HDAEnabler alongside, is there something extra I should enable?

Thanks

**Comment by insanelydeepak** [comment]
provide your codec_dump

**Comment by insanelydeepak** [comment]
so I'm closing this issue till you available .
feel free to re-open whenever required
