### ISSUE TITLE
ALC298 10.11.6 not working (GALAXYBOOK12)

### ISSUE THREAD

**Issue by axel9546** [insanelydeepak/cloverHDA-for-Mac-OS-10.11-El-Capitan#8]
Hello my friend.
I have tried and tested so many things for get audio working!
1st method
CloverHda + Layout13 Patch (Non working)
2nd Method
Patched AppleHDA+Layout13 Patch (Working syspref,fn keys, but NO AUDIO)
3rd Method
AppleALC, Lilu (Clover- Other), CodecCommander (L/E) + Layout13Patch (Working syspref,fn keys, but NO AUDIO)

How to fix the audio of this laptop/tablet?

Also if u need i have some linux codec dump here !! Thanks :) 

[Dumplinux.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-10.11-El-Capitan/files/1394536/Dumplinux.zip)

**Comment by axel9546** [comment]
Up

**Comment by insanelydeepak** [comment]
Hi
i will look in codec dump and let you know

**Comment by axel9546** [comment]
Wow thanks! Appreciated it a lot!
I will wait here :)
Currently running High Sierra 10.13 and also elcapitan (i prefer h.sierra)

**Comment by axel9546** [comment]
@insanelydeepak
Hello mate.
Just to know, did you find something useful from the codex dumps?
Could i help you in some ways :)
Let me know it Thanks

**Comment by insanelydeepak** [comment]
Hi 
can you provide vanilla AppleHDA for 10.11.6 ??

**Comment by axel9546** [comment]
Sorry! Im actually reverted to Mac Os High Sierra if this can help.
With el Capitan i had some problems! Sorry

**Comment by axel9546** [comment]
@insanelydeepak Mac osx High Sierra 10.13 :)

**Comment by axel9546** [comment]
Did u have any news? :)

**Comment by insanelydeepak** [comment]
try this 
layout 13 , disable clover audio patches 
[AppleHDA-280.12-ALC298.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-10.11-El-Capitan/files/1440303/AppleHDA-280.12-ALC298.zip)

**Comment by axel9546** [comment]
Just installed the AppleHda kext In SLE (and rebuilded), and patch 13 on clover,  not working atm
Audio slider working and prefpanel too. But no audio

**Comment by axel9546** [comment]
@insanelydeepak Here is the EFI folder zip if I'm missing something if you could check :) 
[EFI FOLDER.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-10.11-El-Capitan/files/1442702/EFI.FOLDER.zip)

**Comment by insanelydeepak** [comment]
report with these files 
https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/blob/master/TroubleShoot/Troubleshoot%20Reporting.md

**Comment by axel9546** [comment]
Okay thanks! Here are the files! :) @insanelydeepak 
[Files Reporting.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-10.11-El-Capitan/files/1443632/Files.Reporting.zip)

**Comment by insanelydeepak** [comment]
try this file 
just install above kext into 10.12.6 system only not for 10.13 
[Files.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-10.11-El-Capitan/files/1443787/Files.zip)

report with this file 
Screenshot of System Information/Hardware/Audio/Intel High Definition Audio

**Comment by axel9546** [comment]
Ok mate, so i removed the kext provided and overrided with the vanilla (backup) Apple Hda
Then replaced config and dsdt, no audio still, 
In the System information, --> Audio, show "Devices" and black page. No content. 
@insanelydeepak

**Comment by insanelydeepak** [comment]
screenshot ??

**Comment by axel9546** [comment]
@insanelydeepak https://imgur.com/a/2vR6d :)

**Comment by insanelydeepak** [comment]
try this DSDT
post screenshot after restart 
[DSDT.aml.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-10.11-El-Capitan/files/1444253/DSDT.aml.zip)

**Comment by axel9546** [comment]
@insanelydeepak same as before https://imgur.com/a/zBr8F 
If i try with AppleALC kext in clover, it show me this https://imgur.com/a/JJXhP

**Comment by axel9546** [comment]
https://imgur.com/a/uBHn2

**Comment by axel9546** [comment]
Hello did u had any news? :)

**Comment by insanelydeepak** [comment]
really stange , 
try HDAEnaber 13  , https://bitbucket.org/insanelydeepak/hdaenablers-applehda-for-hackintosh/downloads/

**Comment by axel9546** [comment]
Thanks but sorry where to put the kext? 
With current configuration? Or Apple hda patched?

**Comment by axel9546** [comment]
Anyway i tried with DSDT.aml with no patch for layout 13, config plist with no patch for audio, and Hdaenabler kext on SLE.
Reebooted and got nothing changes. 
Hdaenabler kext not loading from what i see on kext wizard

**Comment by insanelydeepak** [comment]
issue is no layout ID injected which issue with HDEF address , just install HDAenbler kext and report with screenshot after it we can goto rest

**Comment by axel9546** [comment]
https://imgur.com/a/dpgKI

**Comment by insanelydeepak** [comment]
ok remove all kexts regarding audio , everything should be vanilla 
best do fresh install and first we make your audio device visible after it can fix your codec issue 

meanwhile try voodooHDA

**Comment by axel9546** [comment]
Ok fresh installed, tryied voodoohda but no results. It says no Voodoohda device found.
So i reinstalled all new vanilla and audio panel in system information is same as before image https://imgur.com/a/dpgKI

If i try to boot with AppleAlc, Lilu and patch 13 in clover appear this https://imgur.com/a/JJXhP

**Comment by insanelydeepak** [comment]
>  https://imgur.com/a/JJXhP

link not working  

> ok remove all kexts regarding audio , everything should be vanilla

remember it dont play with anykext 

use FakePCIID kext and send your origin folder

**Comment by axel9546** [comment]
Fakepciid where in other? Just boot? Thxs

**Comment by insanelydeepak** [comment]
this one 
install or use it from clover folder 
https://bitbucket.org/RehabMan/os-x-fake-pci-id/downloads/

**Comment by insanelydeepak** [comment]
try this 

[Archive.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-10.11-El-Capitan/files/1462294/Archive.zip)

**Comment by axel9546** [comment]
I tried this replaced config and dsdt and give this error https://imgur.com/a/cV4FD

**Comment by insanelydeepak** [comment]
Hi 
do you still have issue , if yes feel free to re-open it , so we can fix this
